### ISSUE TITLE
Usage question: how to work with React lifecycle

### ISSUE THREAD

**Issue by benjycui** [UniversalAvenue/react-compose#8]
It seems that react-compose only works with stateless function component.

**Comment by danielwerthen** [comment]
Hey @benjycui! Sorry for the late response!

The basic usage scenario on our end is to use the stateless components produced by `react-compose` and connect them with `react-redux`, since we use `redux`. Thus, we don't really need to use the lifecycle methods of stateful React components that often. 

When we do need to use something stateful, the preferred approach is to create a higher order component, and wrap the stateless function with that. This allows us to separate the logic and also to a greater extent reuse common stateful patterns across our apps.

**Comment by benjycui** [comment]
Cool, THX.
